### ISSUE TITLE
Add environmental variables

### ISSUE THREAD

**Issue by maddieeckstrom** [quin-tech/full-stack-service-app#22]

**Comment by tonymagr** [comment]
Work completed - database seeded.

**Comment by solangeindaco** [comment]
https://www.npmjs.com/package/dotenv?S_TACT=333AC01A.
The .env file should be on the .gitignore on the server folder

**Comment by tonymagr** [comment]
Made change in server .gitignore - made pull request.

**Comment by tonymagr** [comment]
Fixed again to add .env to server .gitignore, specifically.  Tested successfully.
